### ISSUE TITLE
03demo_translate causes crash

### ISSUE THREAD

**Issue by hlolli** [overtone/shadertone#28] opened 2015-05-22 16:09 UTC
Hi Roger (and other developers)

I've been using shadertone for a while. Now I updated my Linux to use proprietary driver (AMD Catalyst) and it's working wonderfully on my Fedora 21 GNOME, believe it or not (better perfomance etc.) But now I bump into a new problem, when swapping values in shaders, I always bump into the same error. I believe maybe since my new OpenGL version is now 4.4 then it could be that GL20 libraries dont work as they should?

Anyhow when using swap! in demo03 I get this error message (and in many other sceneros as well)
But I know this error would not have been reproduce-able before I installed the Catalyst Driver.

```clojure
Loading shader from string
Reloading shader: nil
Exception in thread "Thread-6" org.lwjgl.opengl.OpenGLException: Invalid operation (1282)
	at org.lwjgl.opengl.Util.checkGLError(Util.java:59)
	at org.lwjgl.opengl.GL20.glUniform3f(GL20.java:356)
	at shadertone.shader$draw.invoke(shader.clj:599)
	at shadertone.shader$update.invoke(shader.clj:697)
	at shadertone.shader$run_thread.invoke(shader.clj:728)
	at shadertone.shader$start_shader_display$fn__3628.invoke(shader.clj:935)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by rogerallen** [comment] 2015-05-23 16:36
@hlolli could you try out "lein test" in the main shadertone directory?  Some dialogs will pop up and you will want to watch stdout to answer the questions.  It would be good to see if an existing test reproduces the error.

**Comment by rogerallen** [comment] 2015-05-23 18:23
FWIW, we'll need to debug which of the reasons listed in the **Errors** section are causing the *Invalid Operation*.

https://www.opengl.org/sdk/docs/man/html/glUniform.xhtml

**Comment by rogerallen** [comment] 2015-05-23 18:30
Oh, never mind the repro steps above--I'm able to repro myself on my MacBook Pro.  :smile:

**Comment by rogerallen** [comment] 2015-05-24 16:52
I've found the issue & should have a bugfix update soon.

**Comment by hlolli** [comment] 2015-05-24 23:09
Ok good! Thanks alot. (just saw your reply now)

I think I will use the swapping alot in performances, had to stick with single shader in my last performance.

**Comment by rogerallen** [comment] 2015-05-25 00:26
Okay, this should be fixed.  Actually, I don't know how it worked before!  I know it did, but I'm not sure what happened.  In any event, I've beefed up my test suite to check this.

Thanks for the bug report.  

Closing.

**Closed by rogerallen** 2015-05-25 00:26 UTC
Labels: bug

**Comment by rogerallen** [comment] 2015-05-25 00:38
p.s. send videos of any performances to the Overtone email list so we can all enjoy them!  :smile:
